ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "reminder30SentAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "reminder10SentAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "reminder5SentAt"  TIMESTAMP(3);
