-- Módulo Gerência: acompanhamento mensal do DRE (BASE GINFO -> linhas
-- normalizadas), com catálogo fixo de contas (nome/setor/grupo/meta AVR) e
-- histórico de lançamentos por mês para comparativo linha a linha.
-- Execute no SQL Editor do Supabase.

-- Catálogo de contas do DRE. O "meta_avr" é a meta oficial (% sobre a
-- receita líquida) para as contas que a empresa acompanha por AVR; fica
-- pré-cadastrado e praticamente não muda durante o ano (confirmado na
-- planilha original: mesma meta em todos os meses).
create table if not exists gerencia_dre_contas (
  conta_codigo text primary key,
  conta_nome text not null,
  setor text,
  grupo text,
  meta_avr numeric,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);
alter table gerencia_dre_contas enable row level security;
create policy "Acesso total" on gerencia_dre_contas for all using (true);

-- Registro de cada importação mensal da aba BASE GINFO, para auditoria.
create table if not exists gerencia_dre_importacoes (
  id uuid primary key default gen_random_uuid(),
  ano integer not null,
  nome_arquivo text,
  total_linhas integer not null default 0,
  importado_por text,
  created_at timestamptz not null default now()
);
alter table gerencia_dre_importacoes enable row level security;
create policy "Acesso total" on gerencia_dre_importacoes for all using (true);

-- Lançamentos por mês/conta, vindos da BASE GINFO. Uma linha por
-- (ano, mes, conta_codigo); reimportar o mesmo mês sobrescreve os valores.
create table if not exists gerencia_dre_lancamentos (
  id uuid primary key default gen_random_uuid(),
  importacao_id uuid references gerencia_dre_importacoes(id) on delete set null,
  ano integer not null,
  mes text not null,
  conta_codigo text not null references gerencia_dre_contas(conta_codigo),
  remunerado numeric not null default 0,
  realizado numeric not null default 0,
  diferenca numeric not null default 0,
  avr_percentual numeric,
  created_at timestamptz not null default now(),
  unique (ano, mes, conta_codigo)
);
alter table gerencia_dre_lancamentos enable row level security;
create policy "Acesso total" on gerencia_dre_lancamentos for all using (true);
create index if not exists idx_gerencia_dre_lancamentos_ano_mes on gerencia_dre_lancamentos(ano, mes);
create index if not exists idx_gerencia_dre_lancamentos_conta on gerencia_dre_lancamentos(conta_codigo);

-- Catálogo inicial das contas (extraído da planilha DRE original), com as
-- metas AVR já oficiais. Linhas futuras criadas automaticamente pela
-- importação (caso surjam contas novas) entram sem meta definida.
insert into gerencia_dre_contas (conta_codigo, conta_nome, setor, grupo, meta_avr, ordem) values
('001', '( = ) RECEITA LÍQUIDA', 'Financeiro', NULL, NULL, 1),
('002', '( = ) RECEITA LÍQUIDA OPERACIONAL', 'Financeiro', 'RECEITA LÍQUIDA', NULL, 2),
('003', '( = ) RECEITA BRUTA COM PRESTAÇÃO DE SERVIÇOS', 'Financeiro', 'RECEITA BRUTA', NULL, 3),
('004', 'PRESTAÇÃO DE SERVIÇOS COM TRANSPORTES PRÓPRIOS', 'Financeiro', NULL, NULL, 4),
('005', 'PRESTAÇÃO DE SERVIÇOS COM TRANSPORTES DE TERCEIROS', 'Financeiro', NULL, NULL, 5),
('006', 'DEDUÇÕES E ABATIMENTOS', 'Financeiro', NULL, NULL, 6),
('007', 'TRIBUTOS SOBRE SERVIÇOS', 'Financeiro', NULL, NULL, 7),
('008', '( - ) COFINS', 'Financeiro', NULL, NULL, 8),
('009', '( - ) PIS', 'Financeiro', NULL, NULL, 9),
('010', '( - ) ICMS', 'Financeiro', NULL, NULL, 10),
('011', '( - ) CONTRIBUIÇÃO PREVIDENCIÁRIA', 'Financeiro', NULL, NULL, 11),
('012', '( - ) ISS', 'Financeiro', NULL, NULL, 12),
('013', 'DESCONTOS E ABATIMENTOS', 'Financeiro', NULL, NULL, 13),
('014', 'DESCONTOS CONCEDIDOS', 'Financeiro', NULL, NULL, 14),
('015', 'DESCONTOS DE DEVOLUÇÃO E INDISPONIBILIDADE', 'Financeiro', NULL, NULL, 15),
('016', 'OUTRAS RECEITAS', 'Financeiro', NULL, NULL, 16),
('017', 'REEMBOLSO ND / OUTRAS RECEITAS', 'Financeiro', NULL, NULL, 17),
('018', 'OUTRAS RECEITAS', 'Financeiro', NULL, NULL, 18),
('019', 'BNS – BÔNUS NÍVEL DE SERVIÇO', 'Financeiro', 'BNS', NULL, 19),
('020', 'REDUÇÃO DE MULTAS E JUROS SOBRE PARCELAMENTOS', 'Financeiro', NULL, NULL, 20),
('021', '( - ) CUSTOS OPERACIONAIS', 'Financeiro', 'AVR', 0.5729, 21),
('022', 'CUSTOS COM TRANSPORTES E TERCEIROS', 'Financeiro', NULL, NULL, 22),
('023', 'FRETE PAGO A TERCEIROS E AGREGADOS', 'Financeiro', NULL, NULL, 23),
('024', 'CARGA E DESCARGA', 'Financeiro', NULL, NULL, 24),
('025', 'SEGURO DE CARGAS', 'Financeiro', NULL, NULL, 25),
('026', 'GERENCIAMENTO DE RISCOS', 'Financeiro', NULL, NULL, 26),
('027', 'CHAPAS E REEMBOLSOS', 'Financeiro', NULL, NULL, 27),
('028', 'GESTÃO CARTÃO FRETE', 'Financeiro', NULL, NULL, 28),
('029', 'OUTROS CUSTOS DE FRETES', 'Financeiro', NULL, NULL, 29),
('030', 'ROYALTIES MARCA COOPERCARGA', 'Financeiro', NULL, NULL, 30),
('033', 'CUSTO COM PESSOAL', 'Gente', 'AVR', -0.3858, 31),
('034', 'GASTOS COM PESSOAL DIRETO', 'Gente', NULL, NULL, 32),
('035', 'SALÁRIOS E ORDENADOS', 'Gente', 'SALÁRIO', NULL, 33),
('036', 'PENSÃO ALIMENTICIA', 'Gente', NULL, NULL, 34),
('037', 'ENCARGOS', 'Gente', NULL, NULL, 35),
('038', 'INSS E PROVISÕES', 'Gente', 'INSS E PROVISÃO', NULL, 36),
('039', 'FGTS E PROVISOES', 'Gente', 'FGTS E PROVISÃO', NULL, 37),
('040', 'FERIAS E PROVISOES', 'Gente', 'FERIAS E PROVISÃO', NULL, 38),
('041', 'DECIMO TERCEIRO SALARIO E PROVISOES', 'Gente', 'DECIMO TERCEIRO E PROVISOES', NULL, 39),
('042', 'PROCESSOS TRABALHISTAS', 'Gente', 'PROCESSOS TRABALHISTAS', NULL, 40),
('043', 'AVISO PRÉVIO', 'Gente', 'AVISO PRÉVIO', NULL, 41),
('044', 'CONTRIBUIÇÃO SINDICAL', 'Gente', NULL, NULL, 42),
('045', 'RESCISOES DIVERSAS', 'Gente', NULL, NULL, 43),
('046', 'OUTRAS DESP. C/ PESSOAL', 'Gente', NULL, NULL, 44),
('047', 'CUSTOS PROC. TRABALHISTAS', 'Gente', NULL, NULL, 45),
('048', 'FGTS S/ RESCISÕES', 'Gente', NULL, NULL, 46),
('049', 'RESSALVA DE RESCISÕES', 'Gente', 'RESSALVA DE RECISOES', NULL, 47),
('050', 'GASTOS COM VALES', 'Gente', NULL, NULL, 48),
('051', 'VALES FINANCEIROS', 'Gente', 'VALES FINANCEIROS', NULL, 49),
('052', 'VALES FISICOS', 'Gente', 'VALES SÍSICOS', NULL, 50),
('053', 'PROCESSO CÍVEL', 'Gente', NULL, NULL, 51),
('054', 'VALES SINISTRO', 'Gente', NULL, NULL, 52),
('055', 'GASTOS COM BENEFICIOS', 'Gente', NULL, NULL, 53),
('056', 'VALE REFEIÇÃO', 'Gente', 'VALE REFEIÇÃO', NULL, 54),
('057', 'VALE TRANSPORTE', 'Gente', 'VALE TRANSPORTE', NULL, 55),
('058', 'PLANO DE SAÚDE', 'Gente', 'PLANO DE SAÚDE', NULL, 56),
('059', 'CESTA BÁSICA', 'Gente', 'CESTA BÁSICA', NULL, 57),
('060', 'CAFÉ DA MANHA', 'Gente', 'CAFÉ DA MANHÃ', NULL, 58),
('061', 'SEGURO DE VIDA', 'Gente', 'SEGURO DE VIDA', NULL, 59),
('062', 'PLR – PARTICIPAÇÃO NOS RESULTADOS', 'Gente', NULL, NULL, 60),
('063', 'PLANO ODONTOLÓGICO', 'Gente', 'PLANO ODONTOLÓGICO', NULL, 61),
('064', 'TAXAS ADM VT/VA', 'Gente', NULL, NULL, 62),
('065', 'CESTA BASICA - CARTÃO', 'Gente', NULL, NULL, 63),
('066', 'INCENTIVOS', 'Gente', 'INCENTIVOS', NULL, 64),
('067', 'OUTRAS DESPESAS - GERAIS - BLOQ', 'Gente', NULL, NULL, 65),
('068', 'GASTOS CONTRATAÇÃO/DEMISSÃO', 'Gente', 'CONTRATAÇÃO /DEMISSÃO', NULL, 66),
('069', 'PCMSO/PPRA', 'Gente', NULL, NULL, 67),
('070', 'EXAMES MÉDICOS', 'Gente', NULL, NULL, 68),
('071', 'DESPESAS RECRUTAMENTO E SELEÇÃO', 'Gente', NULL, NULL, 69),
('072', 'CURSOS E TREINAMENTOS', 'Gente', NULL, NULL, 70),
('073', 'GASTOS COM UNIFORMES E EPI´S', 'EPI', NULL, -0.0089, 71),
('074', 'EPI´S', 'EPI', 'EPI''S', -0.007, 72),
('075', 'UNIFORMES', 'EPI', 'UNIFORME', -0.01, 73),
('076', 'HIGIENIZAÇÃO UNIFORMES', 'EPI', NULL, NULL, 74),
('077', 'KIT HIGIENICO', 'EPI', NULL, NULL, 75),
('078', 'SINISTROS E PEQUENOS ACIDENTES', 'EPI', NULL, NULL, 76),
('079', 'GASTOS COM PESSOAL DE APOIO', 'Gente', NULL, NULL, 77),
('080', 'GASTOS COM SALÁRIOS E ENCARGOS', 'Gente', NULL, NULL, 78),
('081', 'SALÁRIOS', 'Gente', 'SALÁRIO', NULL, 79),
('082', 'ENCARGOS', 'Gente', NULL, NULL, 80),
('083', 'INSS E PROVISÕES', 'Gente', 'INSS E PROVISÃO', NULL, 81),
('084', 'FGTS E PROVISÕES', 'Gente', 'FGTS E PROVISÃO', NULL, 82),
('085', 'FÉRIAS E PROVISÕES', 'Gente', 'FERIAS E PROVISÃO', NULL, 83),
('086', 'DECIMO TERCEIRO SALÁRIO E PROVISÕES', 'Gente', 'DECIMO TERCEIRO E PROVISOES', NULL, 84),
('087', 'PROCESSOS TRABALHISTAS', 'Gente', 'PROCESSOS TRABALHISTAS', NULL, 85),
('088', 'AVISO PRÉVIO', 'Gente', 'AVISO PRÉVIO', NULL, 86),
('089', 'FGTS S/ RESCISÕES', 'Gente', NULL, NULL, 87),
('090', 'GASTOS COM VALES', 'Gente', NULL, NULL, 88),
('091', 'VALES FINANCEIROS', 'Gente', 'VALES FINANCEIROS', NULL, 89),
('092', 'VALES FISICOS', 'Gente', 'VALES SÍSICOS', NULL, 90),
('093', 'GASTOS COM BENEFÍCIOS', 'Gente', NULL, NULL, 91),
('094', 'VALE REFEIÇÃO', 'Gente', 'VALE REFEIÇÃO', NULL, 92),
('095', 'VALE TRANSPORTE', 'Gente', 'VALE TRANSPORTE', NULL, 93),
('096', 'PLANO DE SAÚDE', 'Gente', 'PLANO DE SAÚDE', NULL, 94),
('097', 'CESTA BÁSICA', 'Gente', 'CESTA BÁSICA', NULL, 95),
('098', 'CAFÉ DA MANHÃ', 'Gente', 'CAFÉ DA MANHÃ', NULL, 96),
('099', 'SEGURO DE VIDA', 'Gente', 'SEGURO DE VIDA', NULL, 97),
('100', 'PLR – PARTICIPAÇÃO NOS RESULTADOS', 'Gente', NULL, NULL, 98),
('101', 'PLANO ODONTOLÓGICO', 'Gente', 'PLANO ODONTOLÓGICO', NULL, 99),
('102', 'AUXILIO EDUCAÇÃO', 'Gente', NULL, NULL, 100),
('103', 'GASTOS CONTRATAÇÃO/ DEMISSÃO', 'Gente', 'CONTRATAÇÃO /DEMISSÃO', NULL, 101),
('104', 'PCMSO/PPRA', 'Gente', NULL, NULL, 102),
('105', 'EXAMES MÉDICOS', 'Gente', NULL, NULL, 103),
('106', 'DESPESAS RECRUTAMENTO E SELEÇÃO', 'Gente', NULL, NULL, 104),
('107', 'GASTOS COM UNIFORMES E EPI´S', 'Gente', NULL, NULL, 105),
('108', 'EPI´S', 'Gente', 'EPI''S', NULL, 106),
('109', 'UNIFORMES', 'Gente', 'UNIFORME', NULL, 107),
('110', 'HIGIENIZAÇÃO DE UNIFORMES', 'Gente', NULL, NULL, 108),
('111', 'KIT HIGIENICO', 'Gente', NULL, NULL, 109),
('112', 'SINISTROS E PEQUENOS ACIDENTES', 'Gente', NULL, NULL, 110),
('113', 'CUSTOS GERAIS COM FROTA', 'Frota', 'AVR', -0.1791, 111),
('114', 'CUSTOS VARIÁVEIS FROTA', 'Frota', NULL, NULL, 112),
('115', 'GASTO COM COMBUSTÍVEIS', 'Frota', 'COMBUSTÍVEL', NULL, 113),
('116', 'ÓLEO DIESEL', 'Indicadores RV', NULL, -0.0835, 114),
('117', 'GASTOS COM MANUTENÇÕES', 'Frota', 'MANUTENÇÃO', -0.037, 115),
('118', 'MANUTENÇÃO DE VEICULOS PROPRIOS', 'Frota', NULL, NULL, 116),
('119', 'MANUTENÇÃO SCANIA', 'Frota', NULL, NULL, 117),
('120', 'MANUTENCAO DE CARROCERIA CARRETA', 'Frota', NULL, NULL, 118),
('121', 'LUBRIFICANTES', 'Frota', NULL, NULL, 119),
('122', 'ACESSÓRIOS', 'Frota', NULL, NULL, 120),
('123', 'REBOQUE / GUINCHO', 'Frota', NULL, NULL, 121),
('124', 'AVARIAS E SINISTROS', 'Frota', NULL, NULL, 122),
('125', 'TACOGRAFOS', 'Frota', NULL, NULL, 123),
('126', 'ADESIVAGEM FROTA', 'Frota', NULL, NULL, 124),
('127', 'DESPESAS DIVERSAS FROTA', 'Frota', NULL, NULL, 125),
('128', 'FORRAÇÃO DE CARRETAS', 'Frota', NULL, NULL, 126),
('129', 'AFERIÇÃO TACOGRAFO E FUMAÇA', 'Frota', NULL, NULL, 127),
('130', 'DESCONTO IFOLLOW', 'Frota', NULL, NULL, 128),
('131', 'GASTOS COM PNEUS', 'Frota', NULL, -0.0153, 129),
('132', 'PNEUS', 'Frota', 'PNEUS', NULL, 130),
('133', 'RECAPAGENS', 'Frota', 'RECAPAGENS', NULL, 131),
('134', 'BORRACHARIA', 'Frota', 'BORRACHARIA', NULL, 132),
('135', 'OUTROS GASTOS COM FROTA', 'Frota', NULL, NULL, 133),
('136', 'PEDÁGIOS', 'Frota', 'PEDÁGIO', NULL, 134),
('137', 'MULTAS DE TRÂNSITO', 'Frota', 'MULTAS DE TRÂNSITO', NULL, 135),
('138', 'LAVAÇÃO', 'Frota', 'LAVAÇÃO', NULL, 136),
('139', 'CUSTO FIXOS', 'Frota', NULL, NULL, 137),
('140', 'IPVA/DPVAT E LICENCIAMENTOS', 'Frota', NULL, NULL, 138),
('141', 'SEGURO DE FROTA', 'Frota', NULL, NULL, 139),
('142', 'RASTREAMENTO', 'Frota', 'RASTREAMENTO', NULL, 140),
('143', 'OUTROS CUSTOS OPERACIONAIS', 'Frota', NULL, NULL, 141),
('144', 'MANUTENÇÃO DE CARRINHOS', 'Frota', 'CARRINHO MANUT', NULL, 142),
('145', 'MANUTENÇÃO DE RASTREADORES', 'Gente', NULL, NULL, 143),
('146', 'FRETES E ENCOMENDAS', 'Frota', 'FRETE', NULL, 144),
('147', 'DESPESAS COM VIAGEM', 'Frota', NULL, NULL, 145),
('148', 'SINDICATO PATRONAL', 'Frota', NULL, NULL, 146),
('149', 'TAXAS E IMPOSTOS DIVERSOS', 'Frota', NULL, NULL, 147),
('150', 'OUTRAS DESPESAS OPERACIONAIS', 'Frota', NULL, NULL, 148),
('151', 'ALUGUEL DE EQUIPAMENTOS', 'Frota', 'ALUGUEL DE EQUIPAMENTOS', NULL, 149),
('152', 'MATERIAL DE EXPEDIENTE', 'Financeiro', NULL, NULL, 150),
('153', 'IRRF - RETIDO NA FONTE', 'Financeiro', NULL, NULL, 151),
('154', 'TAXA MENSAL - SEM PARAR', 'Financeiro', NULL, NULL, 152),
('155', 'LUCRO OPERACIONAL VARIÁVEL', 'Financeiro', NULL, NULL, 153),
('156', '( = ) LUCRO OPERACIONAL', 'Financeiro', 'LUCRO', NULL, 154),
('157', '( - ) DESPESAS ADMINISTRATIVAS E FINANCEIRAS', 'Fiannceiro', 'AVR', -0.1049, 155),
('158', 'DESPESAS COM PESSOAL ADMINISTRATIVO', 'Gente ADM', 'AVR', -0.098, 156),
('159', 'SALÁRIOS E PRÓ-LABORE', 'Gente ADM', NULL, NULL, 157),
('160', 'SALÁRIOS', 'Gente ADM', 'SALÁRIO', NULL, 158),
('161', 'PRÓ-LABORE', 'Gente ADM', NULL, NULL, 159),
('162', 'ENCARGOS', 'Gente ADM', NULL, NULL, 160),
('163', 'INSS E PROVISÕES', 'Gente ADM', 'INSS E PROVISÃO', NULL, 161),
('164', 'FGTS E PROVISÕES', 'Gente ADM', 'FGTS E PROVISÃO', NULL, 162),
('165', 'FÉRIAS E PROVISÕES', 'Gente ADM', 'FÉRIAS E PROVISÕES', NULL, 163),
('166', 'DÉCIMO TERCEIRO SALÁRIO E PROVISÕES', 'Gente ADM', NULL, NULL, 164),
('167', 'PROCESSOS TRABALHISTAS', 'Gente ADM', NULL, NULL, 165),
('168', 'AVISO PRÉVIO', 'Gente ADM', 'AVISO PRÉVIO', NULL, 166),
('169', 'CONTRIBUIÇÃO SINDICAL PATRONAL', 'Gente ADM', NULL, NULL, 167),
('170', 'FGTS S/ RESCISÕES', 'Gente ADM', NULL, NULL, 168),
('171', 'GASTOS COM BENEFÍCIOS', 'Gente ADM', NULL, NULL, 169),
('172', 'VALE REFEIÇÃO', 'Gente ADM', 'VALE REFEIÇÃO', NULL, 170),
('173', 'VALE TRANSPORTE', 'Gente ADM', 'VALE TRANSPORTE', NULL, 171),
('174', 'PLANO DE SAÚDE', 'Gente ADM', 'PLANO DE SAÚDE', NULL, 172),
('175', 'CESTA BÁSICA', 'Gente ADM', 'CESTA BÁSICA', NULL, 173),
('176', 'AUXILIO EDUCAÇÃO', 'Gente ADM', NULL, NULL, 174),
('177', 'SEGURO DE VIDA', 'Gente ADM', NULL, NULL, 175),
('178', 'ASSISTÊNCIA MÉDICA E SOCIAL', 'Gente ADM', NULL, NULL, 176),
('179', 'PLANO ODONTOLÓGICO', 'Gente ADM', 'PLANO ODONTOLÓGICO', NULL, 177),
('180', 'CURSOS E TREINAMENTOS', 'Gente ADM', NULL, NULL, 178),
('181', 'PREVIDÊNCIA PRIVADA', 'Gente ADM', NULL, NULL, 179),
('182', 'PLR – PARTICIPAÇÃO NOS RESULTADOS', 'Gente ADM', NULL, NULL, 180),
('183', 'GASTOS CONTRATAÇÃO/DEMISSÃO', 'Gente ADM', NULL, NULL, 181),
('184', 'PCMSO/PPRA', 'Gente ADM', NULL, NULL, 182),
('185', 'EXAMES MÉDICOS', 'Gente ADM', NULL, NULL, 183),
('186', 'DESPESAS RECRUTAMENTO E SELEÇÃO', 'Gente ADM', NULL, NULL, 184),
('187', 'GASTOS COM UNIFORMES E EPI´S', 'Gente ADM', NULL, NULL, 185),
('188', 'EPI´S', 'Gente ADM', 'EPI´S', NULL, 186),
('189', 'UNIFORMES', 'Gente ADM', 'UNIFORME', NULL, 187),
('190', 'DESPESAS ADMINISTRATIVAS GERAIS', 'Financeiro', 'GERAL ADM', -0.0068, 188),
('191', 'HONORÁRIOS PROFISSIONAIS', 'Financeiro', NULL, NULL, 189),
('192', 'DESPESA DE VIAGENS E HOSPEDAGENS', 'Financeiro', NULL, NULL, 190),
('193', 'SISTEMAS DE INFORMÁTICA', 'Financeiro', NULL, NULL, 191),
('194', 'ALUGUÉIS E CONDOMÍNIOS', 'Financeiro', NULL, NULL, 192),
('195', 'ENERGIA ELÉTRICA', 'Financeiro', NULL, NULL, 193),
('196', 'ÁGUA E ESGOTO', 'Financeiro', NULL, NULL, 194),
('197', 'TELEFONE', 'Financeiro', NULL, NULL, 195),
('198', 'INTERNET', 'Financeiro', NULL, NULL, 196),
('199', 'BENS DE PEQUENO VALOR', 'Financeiro', NULL, NULL, 197),
('200', 'MATERIAIS DE EXPEDIENTE', 'Financeiro', NULL, NULL, 198),
('201', 'MATERIAL DE LIMPEZA', 'Financeiro', NULL, NULL, 199),
('202', 'CORREIOS', 'Financeiro', NULL, NULL, 200),
('203', 'CARTÓRIO', 'Financeiro', NULL, NULL, 201),
('204', 'OUTRAS DESPESAS ADMINISTRATIVAS', 'Financeiro', NULL, NULL, 202),
('205', 'MANUTENÇÃO E REPAROS ADMINISTRATIVOS', 'Financeiro', NULL, NULL, 203),
('206', 'IMPRESSOS GRÁFICOS', 'Financeiro', NULL, NULL, 204),
('207', 'DESPESA C/TAXAS E IMPOSTOS', 'Financeiro', NULL, NULL, 205),
('208', 'CONFRATERNIZAÇÃO E EVENTOS', 'Financeiro', NULL, NULL, 206),
('209', 'DESPESAS LEGAIS E JUDICIAIS', 'Financeiro', NULL, NULL, 207),
('210', 'SEGURANÇA E VIGILÂNCIA', 'Financeiro', NULL, NULL, 208),
('211', 'LANCHES, REFEIÇÕES', 'Financeiro', NULL, NULL, 209),
('212', 'DESPESAS COM IMPLANTAÇÃO', 'Financeiro', NULL, NULL, 210),
('213', 'BRINDES DIVERSOS', 'Financeiro', NULL, NULL, 211),
('214', 'DESPESA C/MERCADO', 'Financeiro', NULL, NULL, 212),
('215', 'ROYALTIES', 'Financeiro', NULL, NULL, 213),
('216', 'HONORÁRIOS COM CONSULTORIA DE OPERAÇÕES', 'Financeiro', NULL, NULL, 214),
('217', 'DESPESAS GERAIS FROTA LEVE', 'Frota Leve', NULL, -0.0035, 215),
('218', 'MANUTENÇÃO FROTA LEVE', 'Frota Leve', 'MANUTENÇÃO', 0.0002, 216),
('219', 'COMBUSTÍVEL FROTA LEVE', 'Frota Leve', 'COMBUSTÍVEL', NULL, 217),
('220', 'PNEUS FROTA LEVE', 'Frota Leve', 'PNEUS', NULL, 218),
('221', 'ALUGUEL FROTA LEVE', 'Frota Leve', 'ALUGUEL', NULL, 219),
('222', 'MULTAS FROTA LEVE', 'Frota Leve', 'MULTAS', NULL, 220),
('223', 'IPVA FROTA LEVE', 'Frota Leve', NULL, NULL, 221),
('224', 'SEGURO FROTA LEVE', 'Frota Leve', NULL, NULL, 222),
('225', 'PEDAGIO FROTA LEVE', 'Frota Leve', NULL, NULL, 223),
('226', 'LAVAÇÃO FROTA LEVE', 'Frota Leve', NULL, NULL, 224),
('227', 'OUTRAS DESPESAS FROTA LEVE', 'Frota Leve', NULL, NULL, 225),
('228', '( - ) ALOCAÇÕES MATRIZ', 'Financeiro', NULL, NULL, 226),
('229', '( - ) ALOCAÇÕES CORPORATIVO', 'Financeiro', NULL, NULL, 227),
('230', '( - ) ALOCAÇÕES COMERCIAL', 'Financeiro', NULL, NULL, 228),
('231', '( - ) ALOCAÇÕES BRASIL', 'Financeiro', NULL, NULL, 229),
('232', '( = ) EBITDA', 'Financeiro', 'AVR', 0.3063, 230),
('233', '( - ) CUSTO COM DEPRECIAÇÃO E TRIBUTÁRIOS', 'Financeiro', NULL, NULL, 231),
('234', 'DEPRECIAÇÃO VEÍCULOS', 'Financeiro', NULL, NULL, 232),
('235', 'DEPRECIAÇÃO MAQUINAS E EQUIPAMENTOS', 'Financeiro', NULL, NULL, 233),
('236', 'DEPRECIAÇÃO MOVEIS E UTENSÍLIOS', 'Financeiro', NULL, NULL, 234),
('237', 'ESTORNO ICMS', 'Financeiro', NULL, NULL, 235),
('238', 'ESTORNO DE ICMS IMOBILIZADO', 'Financeiro', NULL, NULL, 236),
('239', '( = ) EBIT', 'Financeiro', NULL, NULL, 237),
('240', '( /- ) RECEITAS/DESPESAS FINANCEIRAS', 'Financeiro', NULL, NULL, 238),
('241', '( - ) DESPESAS FINANCEIRAS', 'Financeiro', NULL, NULL, 239),
('242', 'DESPESAS COM FINAMES', 'Financeiro', NULL, NULL, 240),
('243', 'JUROS DE FINAMES', 'Financeiro', NULL, NULL, 241),
('244', 'JUROS CDC EMPILHADEIRAS', 'Financeiro', NULL, NULL, 242),
('245', 'DESPESAS FINANCEIRAS DIVERSAS', 'Financeiro', NULL, NULL, 243),
('246', 'JUROS COM MÚTUOS E EMPRÉSTIMOS', 'Financeiro', NULL, NULL, 244),
('247', 'JUROS ADIANTAMENTO DE CLIENTE', 'Financeiro', NULL, NULL, 245),
('248', 'JUROS COM MUTUOS DE ACIONISTAS', 'Financeiro', NULL, NULL, 246),
('249', 'JUROS DE LIMITE BANCÁRIO', 'Financeiro', NULL, NULL, 247),
('250', 'DESPESAS BANCÁRIAS', 'Financeiro', NULL, NULL, 248),
('251', 'IOF S/ OPERAÇÕES FINANCEIRAS', 'Financeiro', NULL, NULL, 249),
('252', 'IOF S/ SEGUROS', 'Financeiro', NULL, NULL, 250),
('253', 'JUROS DE FORNECEDORES', 'Financeiro', NULL, NULL, 251),
('254', 'TAXA DE CONSÓRCIO', 'Financeiro', NULL, NULL, 252),
('255', 'REC. DE CRED. BAIXADOS COMO PERDA', 'Financeiro', NULL, NULL, 253),
('256', 'JUROS S/EMPRÉSTIMOS BANCÁRIOS', 'Financeiro', NULL, NULL, 254),
('257', 'JUROS CORREÇÃO SELIC', 'Financeiro', NULL, NULL, 255),
('258', 'OUTRAS DESPESAS', 'Financeiro', NULL, NULL, 256),
('259', 'MULTA E JUROS S/ IMPOSTOS', 'Financeiro', NULL, NULL, 257),
('260', 'DESPESA NÃO -DEDUTIVEL DE IR', 'Financeiro', NULL, NULL, 258),
('261', 'MULTA MINISTÉRIO DO TRABALHO', 'Financeiro', NULL, NULL, 259),
('262', '( ) RECEITAS FINANCEIRAS', 'Financeiro', NULL, NULL, 260),
('263', 'RECEITAS FINANCEIRAS', 'Financeiro', NULL, NULL, 261),
('264', 'JUROS RECEBIDOS', 'Financeiro', NULL, NULL, 262),
('265', 'DESCONTOS OBTIDOS', 'Financeiro', NULL, NULL, 263),
('266', 'JUROS S/APLICAÇÕES FINANCEIRAS', 'Financeiro', NULL, NULL, 264),
('267', 'CORREÇÃO SELIC', 'Financeiro', NULL, NULL, 265),
('268', 'DEDUÇÕES SOBRE RECEITA FINANCEIRA', 'Financeiro', NULL, NULL, 266),
('269', '( - ) PIS SOBRE RECEITA FINANCEIRA', 'Financeiro', NULL, NULL, 267),
('270', '( - ) COFINS SOBRE RECEITA FINANCEIRA', 'Financeiro', NULL, NULL, 268),
('271', '( - ) ALOCAÇÕES FINANCEIRAS', 'Financeiro', NULL, NULL, 269),
('272', '( = ) RESULTADO DO EXERCÍCIO - LUCRO CONTÁBIL', 'Financeiro', NULL, NULL, 270),
('273', '', 'Financeiro', NULL, NULL, 271),
('274', '( - ) PARCELA FINAME', 'Financeiro', NULL, NULL, 272),
('275', '( = ) LUCRO LIQUIDO DO EXERCÍCIO - GERAÇÃO DE CAIXA', 'Financeiro', 'AVR', 0.0272, 273),
('276', '', 'Financeiro', NULL, NULL, 274),
('277', 'DEMONSTRATIVO FRETEIROS', 'Financeiro', NULL, NULL, 275),
('278', '( + ) RECEITA DE TRANSPORTES DE FRETEIROS', 'Financeiro', NULL, NULL, 276),
('279', '( - ) TRIBUTOS SOBRE TRANSPORTE DE FRETEIROS', 'Financeiro', NULL, NULL, 277),
('280', '( = ) RECEITA LIQUIDA DE FRETEIROS', 'Financeiro', NULL, NULL, 278),
('281', '( - ) REPASSE PAGO A FRETEIROS', 'Financeiro', NULL, NULL, 279),
('282', '( = ) LUCRO COM FRETEIROS', 'Financeiro', NULL, NULL, 280)
on conflict (conta_codigo) do update set
  conta_nome = excluded.conta_nome,
  setor = coalesce(excluded.setor, gerencia_dre_contas.setor),
  grupo = coalesce(excluded.grupo, gerencia_dre_contas.grupo),
  meta_avr = coalesce(gerencia_dre_contas.meta_avr, excluded.meta_avr),
  ordem = excluded.ordem;

