-- Módulo Gerência: hierarquia de subtotais do DRE.
-- Extraído lendo as fórmulas reais da aba "DRE" do arquivo original (coluna
-- REALIZADO): algumas contas não vêm direto da BASE GINFO, são somas (ou
-- somas/subtrações) de outras contas específicas. Isso permite montar uma
-- árvore expansível no painel (ex: clicar em "CUSTOS OPERACIONAIS" mostra as
-- contas que compõem aquele total) em vez de listar tudo plano.
-- Execute no SQL Editor do Supabase (depois da migração principal).

alter table gerencia_dre_contas add column if not exists formula_componentes jsonb;

update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"003","sinal":"+"}'::jsonb, '{"codigo":"006","sinal":"+"}'::jsonb) where conta_codigo = '002';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"008","sinal":"+"}'::jsonb, '{"codigo":"009","sinal":"+"}'::jsonb, '{"codigo":"010","sinal":"+"}'::jsonb, '{"codigo":"011","sinal":"+"}'::jsonb, '{"codigo":"012","sinal":"+"}'::jsonb, '{"codigo":"013","sinal":"+"}'::jsonb) where conta_codigo = '006';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"008","sinal":"+"}'::jsonb, '{"codigo":"009","sinal":"+"}'::jsonb, '{"codigo":"010","sinal":"+"}'::jsonb, '{"codigo":"011","sinal":"+"}'::jsonb, '{"codigo":"012","sinal":"+"}'::jsonb) where conta_codigo = '007';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"022","sinal":"+"}'::jsonb, '{"codigo":"034","sinal":"+"}'::jsonb, '{"codigo":"113","sinal":"+"}'::jsonb) where conta_codigo = '021';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"023","sinal":"+"}'::jsonb, '{"codigo":"024","sinal":"+"}'::jsonb, '{"codigo":"025","sinal":"+"}'::jsonb, '{"codigo":"026","sinal":"+"}'::jsonb, '{"codigo":"027","sinal":"+"}'::jsonb, '{"codigo":"028","sinal":"+"}'::jsonb, '{"codigo":"029","sinal":"+"}'::jsonb, '{"codigo":"030","sinal":"+"}'::jsonb) where conta_codigo = '022';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"034","sinal":"+"}'::jsonb, '{"codigo":"079","sinal":"+"}'::jsonb, '{"codigo":"158","sinal":"+"}'::jsonb) where conta_codigo = '033';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"035","sinal":"+"}'::jsonb, '{"codigo":"037","sinal":"+"}'::jsonb, '{"codigo":"050","sinal":"+"}'::jsonb, '{"codigo":"055","sinal":"+"}'::jsonb, '{"codigo":"068","sinal":"+"}'::jsonb, '{"codigo":"073","sinal":"+"}'::jsonb) where conta_codigo = '034';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"038","sinal":"+"}'::jsonb, '{"codigo":"039","sinal":"+"}'::jsonb, '{"codigo":"040","sinal":"+"}'::jsonb, '{"codigo":"041","sinal":"+"}'::jsonb, '{"codigo":"042","sinal":"+"}'::jsonb, '{"codigo":"043","sinal":"+"}'::jsonb, '{"codigo":"044","sinal":"+"}'::jsonb, '{"codigo":"045","sinal":"+"}'::jsonb, '{"codigo":"046","sinal":"+"}'::jsonb, '{"codigo":"047","sinal":"+"}'::jsonb, '{"codigo":"048","sinal":"+"}'::jsonb, '{"codigo":"049","sinal":"+"}'::jsonb) where conta_codigo = '037';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"051","sinal":"+"}'::jsonb, '{"codigo":"052","sinal":"+"}'::jsonb, '{"codigo":"053","sinal":"+"}'::jsonb, '{"codigo":"054","sinal":"+"}'::jsonb) where conta_codigo = '050';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"056","sinal":"+"}'::jsonb, '{"codigo":"057","sinal":"+"}'::jsonb, '{"codigo":"058","sinal":"+"}'::jsonb, '{"codigo":"059","sinal":"+"}'::jsonb, '{"codigo":"060","sinal":"+"}'::jsonb, '{"codigo":"061","sinal":"+"}'::jsonb, '{"codigo":"062","sinal":"+"}'::jsonb, '{"codigo":"063","sinal":"+"}'::jsonb, '{"codigo":"064","sinal":"+"}'::jsonb, '{"codigo":"065","sinal":"+"}'::jsonb, '{"codigo":"066","sinal":"+"}'::jsonb, '{"codigo":"067","sinal":"+"}'::jsonb) where conta_codigo = '055';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"074","sinal":"+"}'::jsonb, '{"codigo":"075","sinal":"+"}'::jsonb, '{"codigo":"076","sinal":"+"}'::jsonb, '{"codigo":"077","sinal":"+"}'::jsonb, '{"codigo":"078","sinal":"+"}'::jsonb) where conta_codigo = '073';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"080","sinal":"+"}'::jsonb, '{"codigo":"082","sinal":"+"}'::jsonb, '{"codigo":"093","sinal":"+"}'::jsonb, '{"codigo":"103","sinal":"+"}'::jsonb, '{"codigo":"107","sinal":"+"}'::jsonb) where conta_codigo = '079';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"084","sinal":"+"}'::jsonb, '{"codigo":"085","sinal":"+"}'::jsonb, '{"codigo":"086","sinal":"+"}'::jsonb, '{"codigo":"087","sinal":"+"}'::jsonb, '{"codigo":"088","sinal":"+"}'::jsonb, '{"codigo":"089","sinal":"+"}'::jsonb, '{"codigo":"090","sinal":"+"}'::jsonb, '{"codigo":"091","sinal":"+"}'::jsonb, '{"codigo":"092","sinal":"+"}'::jsonb, '{"codigo":"093","sinal":"+"}'::jsonb) where conta_codigo = '083';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"114","sinal":"+"}'::jsonb, '{"codigo":"139","sinal":"+"}'::jsonb, '{"codigo":"143","sinal":"+"}'::jsonb) where conta_codigo = '113';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"115","sinal":"+"}'::jsonb, '{"codigo":"117","sinal":"+"}'::jsonb, '{"codigo":"131","sinal":"+"}'::jsonb, '{"codigo":"135","sinal":"+"}'::jsonb) where conta_codigo = '114';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"118","sinal":"+"}'::jsonb, '{"codigo":"119","sinal":"+"}'::jsonb, '{"codigo":"120","sinal":"+"}'::jsonb, '{"codigo":"121","sinal":"+"}'::jsonb, '{"codigo":"122","sinal":"+"}'::jsonb, '{"codigo":"123","sinal":"+"}'::jsonb, '{"codigo":"124","sinal":"+"}'::jsonb, '{"codigo":"125","sinal":"+"}'::jsonb, '{"codigo":"126","sinal":"+"}'::jsonb, '{"codigo":"127","sinal":"+"}'::jsonb, '{"codigo":"128","sinal":"+"}'::jsonb, '{"codigo":"129","sinal":"+"}'::jsonb, '{"codigo":"130","sinal":"+"}'::jsonb) where conta_codigo = '117';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"132","sinal":"+"}'::jsonb, '{"codigo":"133","sinal":"+"}'::jsonb, '{"codigo":"134","sinal":"+"}'::jsonb) where conta_codigo = '131';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"136","sinal":"+"}'::jsonb, '{"codigo":"137","sinal":"+"}'::jsonb, '{"codigo":"138","sinal":"+"}'::jsonb) where conta_codigo = '135';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"140","sinal":"+"}'::jsonb, '{"codigo":"141","sinal":"+"}'::jsonb, '{"codigo":"142","sinal":"+"}'::jsonb) where conta_codigo = '139';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"144","sinal":"+"}'::jsonb, '{"codigo":"145","sinal":"+"}'::jsonb, '{"codigo":"146","sinal":"+"}'::jsonb, '{"codigo":"147","sinal":"+"}'::jsonb, '{"codigo":"148","sinal":"+"}'::jsonb, '{"codigo":"149","sinal":"+"}'::jsonb, '{"codigo":"150","sinal":"+"}'::jsonb, '{"codigo":"151","sinal":"+"}'::jsonb, '{"codigo":"152","sinal":"+"}'::jsonb, '{"codigo":"153","sinal":"+"}'::jsonb, '{"codigo":"154","sinal":"+"}'::jsonb, '{"codigo":"155","sinal":"+"}'::jsonb) where conta_codigo = '143';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"001","sinal":"+"}'::jsonb, '{"codigo":"021","sinal":"+"}'::jsonb) where conta_codigo = '156';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"158","sinal":"+"}'::jsonb, '{"codigo":"190","sinal":"+"}'::jsonb) where conta_codigo = '157';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"160","sinal":"+"}'::jsonb, '{"codigo":"162","sinal":"+"}'::jsonb, '{"codigo":"171","sinal":"+"}'::jsonb, '{"codigo":"183","sinal":"+"}'::jsonb, '{"codigo":"187","sinal":"+"}'::jsonb) where conta_codigo = '158';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"163","sinal":"+"}'::jsonb, '{"codigo":"164","sinal":"+"}'::jsonb, '{"codigo":"165","sinal":"+"}'::jsonb, '{"codigo":"166","sinal":"+"}'::jsonb, '{"codigo":"167","sinal":"+"}'::jsonb, '{"codigo":"168","sinal":"+"}'::jsonb, '{"codigo":"169","sinal":"+"}'::jsonb, '{"codigo":"170","sinal":"+"}'::jsonb) where conta_codigo = '162';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"172","sinal":"+"}'::jsonb, '{"codigo":"173","sinal":"+"}'::jsonb, '{"codigo":"174","sinal":"+"}'::jsonb, '{"codigo":"175","sinal":"+"}'::jsonb, '{"codigo":"176","sinal":"+"}'::jsonb, '{"codigo":"177","sinal":"+"}'::jsonb, '{"codigo":"178","sinal":"+"}'::jsonb, '{"codigo":"179","sinal":"+"}'::jsonb, '{"codigo":"180","sinal":"+"}'::jsonb, '{"codigo":"181","sinal":"+"}'::jsonb, '{"codigo":"182","sinal":"+"}'::jsonb) where conta_codigo = '171';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"184","sinal":"+"}'::jsonb, '{"codigo":"185","sinal":"+"}'::jsonb, '{"codigo":"186","sinal":"+"}'::jsonb) where conta_codigo = '183';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"188","sinal":"+"}'::jsonb, '{"codigo":"189","sinal":"+"}'::jsonb) where conta_codigo = '187';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"191","sinal":"+"}'::jsonb, '{"codigo":"192","sinal":"+"}'::jsonb, '{"codigo":"193","sinal":"+"}'::jsonb, '{"codigo":"194","sinal":"+"}'::jsonb, '{"codigo":"195","sinal":"+"}'::jsonb, '{"codigo":"196","sinal":"+"}'::jsonb, '{"codigo":"197","sinal":"+"}'::jsonb, '{"codigo":"198","sinal":"+"}'::jsonb, '{"codigo":"199","sinal":"+"}'::jsonb, '{"codigo":"200","sinal":"+"}'::jsonb, '{"codigo":"201","sinal":"+"}'::jsonb, '{"codigo":"202","sinal":"+"}'::jsonb, '{"codigo":"203","sinal":"+"}'::jsonb, '{"codigo":"204","sinal":"+"}'::jsonb, '{"codigo":"205","sinal":"+"}'::jsonb, '{"codigo":"206","sinal":"+"}'::jsonb, '{"codigo":"207","sinal":"+"}'::jsonb, '{"codigo":"208","sinal":"+"}'::jsonb, '{"codigo":"209","sinal":"+"}'::jsonb, '{"codigo":"210","sinal":"+"}'::jsonb, '{"codigo":"211","sinal":"+"}'::jsonb, '{"codigo":"212","sinal":"+"}'::jsonb, '{"codigo":"213","sinal":"+"}'::jsonb, '{"codigo":"214","sinal":"+"}'::jsonb, '{"codigo":"215","sinal":"+"}'::jsonb, '{"codigo":"216","sinal":"+"}'::jsonb, '{"codigo":"217","sinal":"+"}'::jsonb) where conta_codigo = '190';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"156","sinal":"+"}'::jsonb, '{"codigo":"157","sinal":"+"}'::jsonb, '{"codigo":"228","sinal":"+"}'::jsonb, '{"codigo":"229","sinal":"+"}'::jsonb, '{"codigo":"231","sinal":"+"}'::jsonb) where conta_codigo = '232';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"243","sinal":"+"}'::jsonb, '{"codigo":"244","sinal":"+"}'::jsonb, '{"codigo":"245","sinal":"+"}'::jsonb) where conta_codigo = '241';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"246","sinal":"+"}'::jsonb, '{"codigo":"247","sinal":"+"}'::jsonb, '{"codigo":"248","sinal":"+"}'::jsonb, '{"codigo":"249","sinal":"+"}'::jsonb, '{"codigo":"250","sinal":"+"}'::jsonb, '{"codigo":"251","sinal":"+"}'::jsonb, '{"codigo":"252","sinal":"+"}'::jsonb, '{"codigo":"253","sinal":"+"}'::jsonb, '{"codigo":"254","sinal":"+"}'::jsonb, '{"codigo":"255","sinal":"+"}'::jsonb, '{"codigo":"256","sinal":"+"}'::jsonb, '{"codigo":"257","sinal":"+"}'::jsonb, '{"codigo":"258","sinal":"+"}'::jsonb, '{"codigo":"259","sinal":"+"}'::jsonb, '{"codigo":"260","sinal":"+"}'::jsonb, '{"codigo":"261","sinal":"+"}'::jsonb) where conta_codigo = '245';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"232","sinal":"+"}'::jsonb, '{"codigo":"233","sinal":"-"}'::jsonb, '{"codigo":"271","sinal":"+"}'::jsonb, '{"codigo":"240","sinal":"+"}'::jsonb) where conta_codigo = '272';
update gerencia_dre_contas set formula_componentes = jsonb_build_array('{"codigo":"272","sinal":"+"}'::jsonb, '{"codigo":"233","sinal":"+"}'::jsonb, '{"codigo":"274","sinal":"-"}'::jsonb) where conta_codigo = '275';
